const KEY='blueKitsuneCommandCenter_v1';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const defaultSubjects=['Maths','Science','English','ICT','Tamil','Hindi','Other'];
const quizBank={
 comprehension:{title:'Comprehension • The Night Library',marks:10,passage:`At the end of the old street stood a library that opened only after sunset. Its windows glowed softly, and each evening a different book was placed on a small table by the door. No one knew who chose the books.\n\nMira began visiting because she liked the quiet. One rainy evening, she found a book with a silver bookmark. Inside was a map of the town, but the map showed places that no longer existed. Mira realised the library was not simply keeping books; it was keeping memories.`,questions:[
  {q:'Why did Mira begin visiting the library?',type:'text',a:['she liked the quiet'],marks:1},
  {q:'When did the library open?',type:'mc',opts:['At sunrise','After sunset','At noon','At midnight'],a:'After sunset',marks:1},
  {q:'What unusual object did Mira find?',type:'text',a:['silver bookmark','book with a silver bookmark'],marks:2},
  {q:'What did the map show?',type:'text',a:['places that no longer existed','places that no longer exist'],marks:2},
  {q:'What does the final sentence suggest about the library?',type:'text',a:['it kept memories','it was keeping memories'],marks:2},
  {q:'Give one word that describes the atmosphere of the passage.',type:'text',a:['quiet','mysterious','mystery','magical','calm'],marks:2}]},
 noteMaking:{title:'Note-making • Saving Water',marks:10,passage:`Water is used every day for drinking, cooking, washing and growing food. Although water covers much of Earth, only a small amount is easily available for people to use.\n\nSimple habits can reduce waste. Turning off a tap while brushing teeth saves water. Fixing leaks prevents clean water from being lost. Collecting rainwater can also provide water for suitable household or garden uses. Communities can help by protecting rivers, reducing pollution and using water carefully during dry periods.`,questions:[
  {q:'Make a short heading for the passage.',type:'text',a:['saving water','water conservation','using water wisely'],marks:2},
  {q:'Write two everyday ways to reduce water waste.',type:'text',a:['turning off a tap while brushing teeth','fixing leaks','collecting rainwater'],marks:2},
  {q:'Why is easily available water limited?',type:'text',a:['only a small amount is easily available','small amount is easily available'],marks:2},
  {q:'Give two community actions mentioned in the passage.',type:'text',a:['protecting rivers','reducing pollution','using water carefully'],marks:2},
  {q:'Write one sentence explaining the main message.',type:'text',a:['use water carefully','reduce water waste','save water'],marks:2}]},
 creative:{title:'Creative Writing • The Door in the Wall',marks:10,prompt:'Write a short story beginning with: “The door had not been there yesterday.” Aim for a clear setting, an interesting problem, descriptive vocabulary and a satisfying ending.'}
};
const EMPTY_STATE={subjects:[...defaultSubjects],school:[],homework:[],everyday:[],exams:[],sessions:[],notes:[],xp:0,quizAttempts:[],chat:[]};
let state=load();
function load(){
 try{
  const current=JSON.parse(localStorage.getItem(KEY)||'null');
  if(current){return {...EMPTY_STATE,...current,subjects:Array.isArray(current.subjects)&&current.subjects.length?current.subjects:[...defaultSubjects],chat:Array.isArray(current.chat)?current.chat:[]};}
  // Compatibility: if the older Blue Kitsune planner exists, carry its useful data forward once.
  const old=JSON.parse(localStorage.getItem('blueKitsuneStudyPlanner_v3')||'null');
  if(old){
   return {...EMPTY_STATE,subjects:Array.isArray(old.subjects)&&old.subjects.length?old.subjects:[...defaultSubjects],everyday:Array.isArray(old.todos)?old.todos.map(t=>({id:t.id||uid('every'),title:t.name||'',subject:t.subject||'Other',done:!!t.completed})):[],homework:Array.isArray(old.homework)?old.homework.map(h=>({id:h.id||uid('hw'),date:h.dueDate||todayISO(),time:h.dueTime||'',subject:h.subject||'Other',task:h.task||'',priority:h.priority||'medium',done:!!h.completed})):[],xp:Number(old.xp)||0};
  }
 }catch(e){}
 return {...EMPTY_STATE};
}
function save(){localStorage.setItem(KEY,JSON.stringify(state));refresh()}
function uid(p='id'){return p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function todayISO(){return new Date().toISOString().slice(0,10)}
function todayName(){return new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date())}
function daysUntil(date){return Math.ceil((new Date(date+'T00:00:00')-new Date(todayISO()+'T00:00:00'))/86400000)}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.add('hidden'),2600)}
function go(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b){e.preventDefault();go(b.dataset.go)}});

function renderHome(){
 const h=new Date().getHours();document.getElementById('greeting').textContent=`Good ${h<12?'morning':h<18?'afternoon':'evening'}, Void Fox.`;
 document.getElementById('todayLine').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date());
 const hw=state.homework.filter(x=>x.date===todayISO()), doneToday=hw.filter(x=>x.done).length+state.everyday.filter(x=>x.doneToday===todayISO()).length, totalToday=hw.length+state.everyday.length, pct=totalToday?Math.round(doneToday/totalToday*100):0;
 document.getElementById('homeProgress').textContent=pct+'%';document.getElementById('homeHW').textContent=hw.filter(x=>!x.done).length;document.getElementById('homeXP').textContent=state.xp;
 const ex=state.exams.filter(e=>daysUntil(e.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))[0];document.getElementById('homeExam').textContent=ex?`${daysUntil(ex.date)}d`:'—';document.getElementById('homeExamSub').textContent=ex?`${ex.subject} • ${formatDate(ex.date)}`:'No upcoming exam';
 const classes=state.school.filter(x=>x.day===todayName()).sort((a,b)=>a.time.localeCompare(b.time));document.getElementById('todayClasses').innerHTML=classes.length?classes.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.time)} • ${esc(x.subject)}</div><div class="item-meta">${esc(x.room||'')}</div></div></div>`).join(''):`<div class="muted">No school periods added for today.</div>`;
 document.getElementById('todayHomework').innerHTML=hw.length?hw.map(x=>taskHTML(x,true)).join(''):`<div class="muted">No homework scheduled today. Nice. 🦊</div>`;
 const ups=state.exams.filter(e=>daysUntil(e.date)>=0).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);document.getElementById('upcomingExams').innerHTML=ups.length?ups.map(e=>`<div class="item"><div class="item-main"><div class="item-title">${esc(e.subject)}</div><div class="item-meta">${formatDate(e.date)} • ${daysUntil(e.date)} day${daysUntil(e.date)==1?'':'s'} left</div></div></div>`).join(''):`<div class="muted">No upcoming exams yet.</div>`;
 renderSuggestion('nextAction');
}
function taskHTML(x,hw=false){return `<div class="item"><input class="check" type="checkbox" ${x.done?'checked':''} data-${hw?'hw':'every'}-done="${x.id}"><div class="item-main"><div class="item-title ${x.done?'status-done':''}">${esc(hw?x.task:x.title)}</div><div class="item-meta">${hw?esc(x.subject)+' • '+formatDate(x.date):'Everyday task'}</div></div><button class="mini" data-${hw?'hw':'every'}-edit="${x.id}">✎</button><button class="mini delete" data-${hw?'hw':'every'}-delete="${x.id}">×</button></div>`}
function renderSuggestion(id){const box=document.getElementById(id);if(!box)return;const suggestions=[];const todayHW=state.homework.filter(x=>x.date===todayISO()&&!x.done).sort(prioritySort);if(todayHW[0])suggestions.push({title:todayHW[0].task,meta:`${todayHW[0].subject} • homework today`,go:'homework',score:100});const upcoming=state.exams.filter(e=>daysUntil(e.date)>=0).sort((a,b)=>daysUntil(a.date)-daysUntil(b.date))[0];if(upcoming)suggestions.push({title:`Revise ${upcoming.subject}`,meta:`Exam in ${daysUntil(upcoming.date)} day${daysUntil(upcoming.date)==1?'':'s'} • ${upcoming.topic||'your chosen topic'}`,go:'exams',score:90-Math.max(0,daysUntil(upcoming.date))});
 const todo=state.everyday.find(x=>!x.done);if(todo)suggestions.push({title:todo.title,meta:'Everyday task',go:'everyday',score:50});const session=state.sessions.filter(s=>s.date===todayISO()).sort((a,b)=>a.time.localeCompare(b.time))[0];if(session)suggestions.push({title:`Study ${session.subject}`,meta:`${session.time} • ${session.topic||'revision session'}`,go:'focus',score:85});suggestions.sort((a,b)=>b.score-a.score);const s=suggestions[0];box.innerHTML=s?`<h3>🦊 ${esc(s.title)}</h3><p class="muted">${esc(s.meta)}</p><button class="ghost" data-go="${s.go}">Open it →</button>`:`<h3>You're clear for now ✦</h3><p class="muted">Use this free time for a small revision session, reading, or a proper break.</p>`}
function prioritySort(a,b){return ({high:0,medium:1,low:2}[a.priority]??1)-({high:0,medium:1,low:2}[b.priority]??1)}
function formatDate(s){if(!s)return'—';return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T00:00:00'))}

function renderSchool(){const body=document.getElementById('schoolBody');const rows=[...state.school].sort((a,b)=>days.indexOf(a.day)-days.indexOf(b.day)||a.time.localeCompare(b.time));body.innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.day)}</td><td>${esc(x.time)}</td><td>${esc(x.subject)}</td><td>${esc(x.room||'')}</td><td><button class="mini" data-school-edit="${x.id}">✎</button> <button class="mini delete" data-school-delete="${x.id}">×</button></td></tr>`).join(''):`<tr><td colspan="5" class="muted">No periods yet. Add your school timetable here.</td></tr>`}
function renderHomework(){const body=document.getElementById('hwBody');const rows=[...state.homework].sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||'')||a.subject.localeCompare(b.subject));document.getElementById('hwCount').textContent=rows.length;body.innerHTML=rows.length?rows.map(x=>`<tr><td>${formatDate(x.date)}</td><td>${esc(x.time||'—')}</td><td>${esc(x.subject)}</td><td>${esc(x.task)}</td><td class="priority-${x.priority}">${esc(x.priority)}</td><td><label><input class="check" type="checkbox" ${x.done?'checked':''} data-hw-done="${x.id}"> ${x.done?'Done':'Open'}</label></td><td><button class="mini" data-hw-edit="${x.id}">✎</button> <button class="mini delete" data-hw-delete="${x.id}">×</button></td></tr>`).join(''):`<tr><td colspan="7" class="muted">No homework yet.</td></tr>`;const schedule=document.getElementById('homeworkSchedule');schedule.innerHTML=rows.length?rows.map(x=>`<div class="schedule-row"><div class="schedule-date"><b>${formatDate(x.date)}</b><small>${esc(x.time||'Flexible')}</small></div><div class="schedule-dot"></div><div class="item-main"><div class="item-title">${esc(x.subject)} • ${esc(x.task)}</div><div class="item-meta">${esc(x.priority)} priority • ${x.done?'Completed':'Planned'}</div></div></div>`).join(''):`<div class="muted">No scheduled homework blocks yet.</div>`;renderSubjects()}
function renderSubjects(){document.getElementById('subjectOptions').innerHTML=state.subjects.map(s=>`<option value="${esc(s)}">`).join('');document.getElementById('subjectsList').innerHTML=state.subjects.map(s=>`<div class="chip"><span>${esc(s)}</span><button data-subject-edit="${esc(s)}">✎</button><button data-subject-delete="${esc(s)}">×</button></div>`).join('')}

function renderEveryday(){const q=document.getElementById('everydaySearch').value.toLowerCase();const filter=document.getElementById('everydayFilter').value;const rows=state.everyday.filter(x=>(x.title+' '+(x.notes||'')).toLowerCase().includes(q)&&(filter==='all'||(filter==='done'?x.done:!x.done)));const open=state.everyday.filter(x=>!x.done),done=state.everyday.filter(x=>x.done);document.getElementById('everyOpenCount').textContent=open.length;document.getElementById('everyDoneCount').textContent=done.length;document.getElementById('everyOpen').innerHTML=filter==='done'?'':(filter==='all'||filter==='open'?rows.filter(x=>!x.done).map(x=>taskHTML(x)).join(''):'');document.getElementById('everyDone').innerHTML=filter==='open'?'':(filter==='all'||filter==='done'?rows.filter(x=>x.done).map(x=>taskHTML(x)).join(''):'');if(!document.getElementById('everyOpen').innerHTML)document.getElementById('everyOpen').innerHTML='<div class="muted">Nothing here.</div>';if(!document.getElementById('everyDone').innerHTML)document.getElementById('everyDone').innerHTML='<div class="muted">Nothing here.</div>'}

function renderExams(){const cards=document.getElementById('examCards');const exams=[...state.exams].sort((a,b)=>a.date.localeCompare(b.date));cards.innerHTML=exams.length?exams.map(e=>{const d=daysUntil(e.date);const pct=d<=0?100:Math.max(0,Math.min(100,100-d*3));return `<article class="panel exam-card"><span class="eyebrow">${esc(e.subject)}</span><div class="date">${formatDate(e.date)}</div><div class="days">${d<0?'Past exam':d===0?'Today':d+' days to go'}</div><p class="muted">${esc(e.topic||'No main topic added')}</p><div class="bar"><i style="width:${pct}%"></i></div><div class="exam-actions"><button class="mini" data-exam-edit="${e.id}">Edit</button><button class="mini delete" data-exam-delete="${e.id}">Delete</button></div></article>`}).join(''):`<div class="panel"><div class="muted">No exams added. Add your first exam and then build revision sessions.</div></div>`;const body=document.getElementById('sessionBody');body.innerHTML=state.sessions.sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)).map(s=>`<tr><td>${formatDate(s.date)}</td><td>${esc(s.time)}</td><td>${esc(s.subject)}</td><td>${esc(s.topic||'')}</td><td>${esc(state.exams.find(e=>e.id===s.examId)?.subject||'')}</td><td><button class="mini delete" data-session-delete="${s.id}">×</button></td></tr>`).join('')||`<tr><td colspan="6" class="muted">No revision sessions yet.</td></tr>`}

function renderEnglish(type='comprehension'){document.querySelectorAll('[data-english]').forEach(b=>b.classList.toggle('active',b.dataset.english===type));const p=document.getElementById('englishPanel');if(type==='creative'){p.innerHTML=`<article class="panel quiz-panel"><span class="eyebrow">10 MARKS • ORIGINAL WRITING TASK</span><h2>${quizBank.creative.title}</h2><p>${esc(quizBank.creative.prompt)}</p><label>Your response<textarea id="creativeAnswer" rows="18" placeholder="Write your story here..."></textarea></label><div class="modal-actions"><button class="primary" id="saveCreative">Save practice</button></div><div id="creativeResult" class="result hidden"></div></article>`;return}const q=type==='notes'?quizBank.noteMaking:quizBank.comprehension;p.innerHTML=`<article class="panel quiz-panel"><span class="eyebrow">${q.marks} MARKS • ORIGINAL PRACTICE</span><h2>${q.title}</h2><div class="passage">${esc(q.passage)}</div><form id="englishQuiz">${q.questions.map((x,i)=>`<div class="question"><span class="mark">${x.marks} mark${x.marks===1?'':'s'}</span><b>${i+1}. ${esc(x.q)}</b>${x.type==='mc'?x.opts.map(o=>`<label><input type="radio" name="q${i}" value="${esc(o)}"> ${esc(o)}</label>`).join(''):`<textarea name="q${i}" rows="2" placeholder="Your answer..."></textarea>`}</div>`).join('')}<div class="modal-actions"><button class="primary">Submit practice</button></div></form><div id="englishResult" class="result hidden"></div></article>`;document.getElementById('englishQuiz').addEventListener('submit',e=>{e.preventDefault();let score=0;q.questions.forEach((x,i)=>{const el=e.currentTarget.elements['q'+i];const val=el?.value?.trim().toLowerCase()||'';if(x.a.some(a=>val===a.toLowerCase()||val.includes(a.toLowerCase())))score+=x.marks});state.xp+=score;state.quizAttempts.push({id:uid('attempt'),title:q.title,score,max:q.marks,date:new Date().toISOString()});save();const r=document.getElementById('englishResult');r.classList.remove('hidden');r.innerHTML=`<b>Score: ${score} / ${q.marks}</b><br>+${score} XP ✦<br><span class="small">For written answers, compare your response with the passage and improve clarity, evidence and detail.</span>`})}

function renderNotes(){const list=document.getElementById('notesList');list.innerHTML=state.notes.length?[...state.notes].reverse().map(n=>`<div class="note-card" data-note-open="${n.id}"><span class="eyebrow">${esc(n.subject)}</span><h3>${esc(n.title)}</h3><div class="note-preview">${esc(n.body.replace(/\n/g,' '))}</div></div>`).join(''):`<div class="muted">No saved notes yet.</div>`}
function smartDraft(prompt){const clean=prompt.trim();if(!clean)return'';const topic=clean.replace(/^(make|create|give|write)\s+(grade\s*8\s*)?(notes?|a study guide)\s*(on|about|for)?\s*/i,'').trim()||clean;return `# ${topic}\n\n## 1. Key idea\nWrite the central idea of ${topic} in one clear sentence.\n\n## 2. Key definitions\n• Term 1 — add a short definition.\n• Term 2 — add a short definition.\n• Term 3 — add a short definition.\n\n## 3. Main points\n• Break the topic into 3–5 important points.\n• Keep each point short and specific.\n• Add an example wherever it helps.\n\n## 4. Common mistakes\n• Watch for confusing similar terms.\n• Check units, keywords or evidence where relevant.\n\n## 5. Quick revision questions\n1. What is the most important definition?\n2. Explain the topic in your own words.\n3. Give one example.\n4. What mistake should you avoid?\n5. What would an exam question about this topic ask?\n\nAI note: This is an offline structured starter. For factual, topic-specific notes, open ChatGPT with the prompt and save the finished answer here.`}

function openModal(title,body,onSave){const m=document.getElementById('modal'),c=document.getElementById('modalContent');c.innerHTML=`<span class="eyebrow">${title}</span>${body}<div class="modal-actions"><button class="primary" id="modalSave">Save</button></div>`;m.classList.remove('hidden');document.getElementById('modalSave').onclick=()=>{if(onSave())m.classList.add('hidden')}}document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.add('hidden');
function editSchool(id){const x=state.school.find(v=>v.id===id)||{day:todayName(),time:'08:00',subject:'',room:''};openModal('SCHOOL PERIOD',`<div class="form-grid"><label>Day<select id="mDay">${days.map(d=>`<option ${d===x.day?'selected':''}>${d}</option>`).join('')}</select></label><label>Time<input id="mTime" type="time" value="${esc(x.time)}"></label></div><label>Subject / Class<input id="mSubject" value="${esc(x.subject)}"></label><label>Room<input id="mRoom" value="${esc(x.room||'')}"></label>`,()=>{const data={id:id||uid('period'),day:mDay.value,time:mTime.value,subject:mSubject.value.trim(),room:mRoom.value.trim()};if(!data.subject){toast('Add a subject first.');return false}if(id)Object.assign(state.school.find(v=>v.id===id),data);else state.school.push(data);save();toast('🏫 School timetable updated.');return true})}
function editHW(id){const x=state.homework.find(v=>v.id===id)||{date:todayISO(),subject:state.subjects[0],task:'',priority:'medium'};openModal('HOMEWORK',`<div class="form-grid"><label>Day / Date<input id="mDate" type="date" value="${esc(x.date)}"></label><label>Study time<input id="mTime" type="time" value="${esc(x.time||'')}"></label></div><label>Subject<select id="mSubject">${state.subjects.map(s=>`<option ${s===x.subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Homework<textarea id="mTask" rows="4">${esc(x.task)}</textarea></label><label>Priority<select id="mPriority"><option value="high" ${x.priority==='high'?'selected':''}>High</option><option value="medium" ${x.priority==='medium'?'selected':''}>Medium</option><option value="low" ${x.priority==='low'?'selected':''}>Low</option></select></label>`,()=>{const data={id:id||uid('hw'),date:mDate.value,time:mTime.value,subject:mSubject.value,task:mTask.value.trim(),priority:mPriority.value,done:x.done||false};if(!data.task||!data.date){toast('Add a date and homework task.');return false}const other=state.homework.filter(v=>v.date===data.date&&v.subject!==data.subject&&!id);if(other.length>=2){toast('Only 2 different subjects can be planned for one day.');return false}if(id)Object.assign(state.homework.find(v=>v.id===id),data);else state.homework.push(data);save();toast('📚 Homework saved.');return true})}
function editEvery(id){const x=state.everyday.find(v=>v.id===id)||{title:'',notes:''};openModal('EVERYDAY TASK',`<label>Task<input id="mTitle" value="${esc(x.title)}"></label><label>Notes<input id="mNotes" value="${esc(x.notes||'')}"></label>`,()=>{const data={id:id||uid('task'),title:mTitle.value.trim(),notes:mNotes.value.trim(),done:x.done||false};if(!data.title){toast('Give the task a name.');return false}if(id)Object.assign(state.everyday.find(v=>v.id===id),data);else state.everyday.push(data);save();return true})}
function editExam(id){const x=state.exams.find(v=>v.id===id)||{subject:state.subjects[0],date:todayISO(),topic:''};openModal('EXAM',`<label>Subject<select id="mSubject">${state.subjects.map(s=>`<option ${s===x.subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Exam date<input id="mDate" type="date" value="${esc(x.date)}"></label><label>Main topic / chapters<input id="mTopic" value="${esc(x.topic||'')}"></label>`,()=>{const data={id:id||uid('exam'),subject:mSubject.value,date:mDate.value,topic:mTopic.value.trim()};if(!data.date){toast('Choose an exam date.');return false}if(id)Object.assign(state.exams.find(v=>v.id===id),data);else state.exams.push(data);save();toast('🎯 Exam plan updated.');return true})}
function editSession(){openModal('REVISION SESSION',`<label>Date<input id="mDate" type="date" value="${todayISO()}"></label><div class="form-grid"><label>Time<input id="mTime" type="time" value="17:00"></label><label>Subject<select id="mSubject">${state.subjects.map(s=>`<option>${esc(s)}</option>`).join('')}</select></label></div><label>Topic<input id="mTopic"></label><label>Exam<select id="mExam">${state.exams.map(e=>`<option value="${e.id}">${esc(e.subject)} • ${formatDate(e.date)}</option>`).join('')}</select></label>`,()=>{const d={id:uid('session'),date:mDate.value,time:mTime.value,subject:mSubject.value,topic:mTopic.value.trim(),examId:mExam.value};if(!d.date||!d.examId){toast('Add an exam and date first.');return false}state.sessions.push(d);save();toast('📖 Revision session added.');return true})}
function editNote(id){const n=state.notes.find(v=>v.id===id);if(n){noteId.value=n.id;noteTitle.value=n.title;noteSubject.value=n.subject;noteBody.value=n.body;document.getElementById('noteMode').textContent='EDIT NOTE';document.getElementById('noteBody').focus()}}

function plannerContext(){
 const todayHW=state.homework.filter(x=>x.date===todayISO()&&!x.done).slice(0,4);
 const nextExam=state.exams.filter(e=>daysUntil(e.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))[0];
 const classes=state.school.filter(x=>x.day===todayName()).sort((a,b)=>a.time.localeCompare(b.time)).slice(0,5);
 return {homework:todayHW.map(x=>`${x.subject}: ${x.task}`),nextExam:nextExam?`${nextExam.subject} on ${formatDate(nextExam.date)}${nextExam.topic?' ('+nextExam.topic+')':''}`:'none',classes:classes.map(x=>`${x.time} ${x.subject}`),openTasks:state.everyday.filter(x=>!x.done).slice(0,4).map(x=>x.title)};
}
function buddyReply(msg){
 const m=msg.toLowerCase(), c=plannerContext();
 if(m.includes('gossip')||m.includes('rumour')||m.includes('rumor')||m.includes('friend')||m.includes('drama')) return `Okay, tell me what happened — no judgement. 🦊 I can help you figure out what to say, whether to stay out of the drama, or how to handle a friend situation without making it bigger. If it's just a rumour about someone, I'd avoid spreading it until you know it's true.`;
 if(m.includes('hello')||m.includes('hi')||m.includes('hey')) return `Heyyy Void Fox 🦊💙 What's going on? We can study, plan your evening, talk about school stuff, or just chat.`;
 if(m.includes('30 minutes')||m.includes('free')||m.includes('what should i study')||m.includes('what should i do')){
  if(c.homework[0]) return `You have a 30-minute window. I'd start with **${c.homework[0]}**. 🦊 Do 20 minutes of focused work, 5 minutes checking your answer, then 5 minutes to pack up or take a proper break.`;
  if(c.nextExam!=='none') return `You're clear of today's homework, so I'd use 30 minutes for your nearest exam: **${c.nextExam}**. Do 20 minutes of revision + 10 minutes of active recall or a mini quiz.`;
  return `Nothing urgent is showing up. 🌙 Use 20 minutes for a small revision/quiz and keep the last 10 minutes as a real break. Free time does not have to become study time every time.`;
 }
 if(m.includes('quiz')) return `Absolutely. Tell me the subject + chapter (for example, “Grade 8 Maths: simultaneous equations”) and I'll give you questions one at a time, wait for your answer, then mark and explain them.`;
 if(m.includes('explain')||m.includes('understand')||m.includes('question')) return `Yep. Send me the topic or paste the question. I'll break it into small Grade 8-friendly steps, explain the tricky part, then give you one quick check question.`;
 if(m.includes('tonight')||m.includes('plan')){const parts=[];if(c.homework[0])parts.push(`finish ${c.homework[0]}`);if(c.nextExam!=='none')parts.push(`do a short revision block for ${c.nextExam}`);if(c.openTasks[0])parts.push(`then handle ${c.openTasks[0]}`);return parts.length?`Let's keep tonight realistic: 1) ${parts.join(' → ')}. Then stop and give yourself some proper downtime. 💙`:`You're pretty clear tonight. Do one useful study block if you want, then enjoy your free time.`}
 if(m.includes('notes')) return `Give me the topic and what you need — definitions, examples, key points, exam questions, flashcards, or a one-page revision sheet. I can structure it for you.`;
 if(m.includes('stressed')||m.includes('overwhelmed')||m.includes('tired')) return `Okay, pause for a second. 🦊 You don't need to solve the whole week at once. Tell me what is due first and how much time you actually have, and we'll make a small plan.`;
 if(m.includes('thank')) return `Anytimeee 💙 Now go do the tiny next step, not the entire universe.`;
 return `I'm listening. 🦊 You can ask me about schoolwork, exams, homework, planning, notes, friends or school drama, or you can literally just chat. If you want a full ChatGPT-level answer, tap “Open full ChatGPT” and I'll carry your request + useful planner context over.`;
}
function addChat(text,who,saveIt=true){const log=document.getElementById('chatLog');if(!log)return;const d=document.createElement('div');d.className='bubble '+who;d.textContent=text;log.appendChild(d);log.scrollTop=log.scrollHeight;if(saveIt){state.chat=state.chat||[];state.chat.push({text,who,at:Date.now()});if(state.chat.length>80)state.chat=state.chat.slice(-80);localStorage.setItem(KEY,JSON.stringify(state));}}
function renderChat(){const log=document.getElementById('chatLog');if(!log)return;log.innerHTML='';const history=state.chat||[];if(!history.length){addChat(`Heyyy Void Fox 🦊💙 I'm your Kitsune Buddy. Ask me about studying, exams, homework, planning, notes, school gossip, friends, or just chat. What's going on?`,'bot',false);return;}history.forEach(x=>addChat(x.text,x.who,false));}
function sendChat(){const i=document.getElementById('chatInput'),v=i.value.trim();if(!v)return;addChat(v,'user');i.value='';setTimeout(()=>addChat(buddyReply(v),'bot'),250)}

// Events
addPeriod.onclick=()=>editSchool();addHW.onclick=()=>editHW();addEveryday.onclick=()=>editEvery();addExam.onclick=()=>editExam();addSession.onclick=()=>editSession();newNote.onclick=()=>{noteForm.reset();noteId.value='';document.getElementById('noteMode').textContent='NEW NOTE'};
everydaySearch.oninput=renderEveryday;everydayFilter.onchange=renderEveryday;guideNow.onclick=()=>{renderSuggestion('nextAction');document.getElementById('nextAction').scrollIntoView({behavior:'smooth',block:'center'})};guideFocus.onclick=()=>{renderSuggestion('focusSuggestion')};
document.getElementById('subjectForm').onsubmit=e=>{e.preventDefault();const n=subjectName.value.trim();if(n&&!state.subjects.includes(n)){state.subjects.push(n);save();subjectName.value='';toast('Subject added.')}else toast('That subject already exists.');};
document.getElementById('noteForm').onsubmit=e=>{e.preventDefault();const id=noteId.value;if(id){Object.assign(state.notes.find(n=>n.id===id),{title:noteTitle.value.trim(),subject:noteSubject.value.trim(),body:noteBody.value.trim()})}else state.notes.push({id:uid('note'),title:noteTitle.value.trim(),subject:noteSubject.value.trim(),body:noteBody.value.trim()});save();toast('📝 Note saved.');document.getElementById('noteMode').textContent='NEW NOTE';};
makeNotes.onclick=()=>{const d=smartDraft(aiPrompt.value);if(!d){toast('Give me a topic or prompt first.');return}noteTitle.value=aiPrompt.value.trim().slice(0,70);noteSubject.value='AI Notes';noteBody.value=d;document.getElementById('noteMode').textContent='AI DRAFT';document.getElementById('noteBody').focus()};
function aiUrl(prompt){return 'https://chatgpt.com/?q='+encodeURIComponent(prompt)}
openAI.onclick=()=>{const p=aiPrompt.value.trim()||'Help me study. Ask what I am learning, then make a Grade 8 study plan with explanations, practice questions and a short quiz.';window.open(aiUrl(`Act as my Grade 8 study buddy. Be friendly, age-appropriate and concise. Help with this request: ${p}`),'_blank')};chatGPT.onclick=()=>{const c=plannerContext();const prompt=`Act as my friendly Grade 8 study-and-life buddy. Help with studying, school planning, friends/school gossip and everyday chatting. Be supportive, age-appropriate and do not encourage harmful or risky behaviour.

My current planner context:
Today's homework: ${c.homework.join(' | ')||'none'}
Nearest exam: ${c.nextExam}
Today's classes: ${c.classes.join(' | ')||'none'}
Open everyday tasks: ${c.openTasks.join(' | ')||'none'}

Start by responding to what I ask next.`;window.open(aiUrl(prompt),'_blank')};sendChat.onclick=sendChat;chatInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}});clearChat.onclick=()=>{if(confirm('Clear your Buddy chat history? Your homework, exams, notes and other planner data will stay safe.')){state.chat=[];localStorage.setItem(KEY,JSON.stringify(state));renderChat()}};document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>{chatInput.value=b.dataset.chat;sendChat()});
document.querySelectorAll('[data-english]').forEach(b=>b.onclick=()=>renderEnglish(b.dataset.english));
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.schoolEdit)editSchool(t.dataset.schoolEdit);if(t.dataset.schoolDelete){state.school=state.school.filter(x=>x.id!==t.dataset.schoolDelete);save()}if(t.dataset.hwEdit)editHW(t.dataset.hwEdit);if(t.dataset.hwDelete){state.homework=state.homework.filter(x=>x.id!==t.dataset.hwDelete);save()}if(t.dataset.everyEdit)editEvery(t.dataset.everyEdit);if(t.dataset.everyDelete){state.everyday=state.everyday.filter(x=>x.id!==t.dataset.everyDelete);save()}if(t.dataset.examEdit)editExam(t.dataset.examEdit);if(t.dataset.examDelete){state.exams=state.exams.filter(x=>x.id!==t.dataset.examDelete);state.sessions=state.sessions.filter(x=>x.examId!==t.dataset.examDelete);save()}if(t.dataset.sessionDelete){state.sessions=state.sessions.filter(x=>x.id!==t.dataset.sessionDelete);save()}if(t.dataset.subjectEdit){const old=t.dataset.subjectEdit,n=prompt('Rename subject:',old);if(n&&n.trim()&&n.trim()!==old){const nn=n.trim();state.subjects=state.subjects.map(s=>s===old?nn:s);state.homework.forEach(x=>{if(x.subject===old)x.subject=nn});state.everyday.forEach(x=>{});state.exams.forEach(x=>{if(x.subject===old)x.subject=nn});state.sessions.forEach(x=>{if(x.subject===old)x.subject=nn});save()}}if(t.dataset.subjectDelete){if(state.subjects.length<=1){toast('Keep at least one subject.');return}const n=t.dataset.subjectDelete;state.subjects=state.subjects.filter(s=>s!==n);save();toast('Subject removed from pickers. Existing items keep their text.')}if(t.dataset.noteOpen)editNote(t.dataset.noteOpen)});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.hwDone){const x=state.homework.find(v=>v.id===t.dataset.hwDone);if(x&&!x.done&&t.checked)state.xp+=10;if(x)x.done=t.checked;save()}if(t.dataset.everyDone){const x=state.everyday.find(v=>v.id===t.dataset.everyDone);if(x&&!x.done&&t.checked){x.doneToday=todayISO();state.xp+=5}x.done=t.checked;save()}});
// Focus timer
let timer={seconds:1500,total:1500,running:false,int:null};function timerRender(){timerDisplay.textContent=`${String(Math.floor(timer.seconds/60)).padStart(2,'0')}:${String(timer.seconds%60).padStart(2,'0')}`};document.querySelectorAll('.presets button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.presets button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');timer.total=Number(b.dataset.min)*60;timer.seconds=timer.total;timerRender()});timerStart.onclick=()=>{if(timer.running){clearInterval(timer.int);timer.running=false;timerStart.textContent='Start';return}timer.running=true;timerStart.textContent='Pause';timer.int=setInterval(()=>{timer.seconds--;timerRender();if(timer.seconds<=0){clearInterval(timer.int);timer.running=false;timerStart.textContent='Start';state.xp+=10;save();toast('⏱ Focus quest complete! +10 XP')}} ,1000)};timerReset.onclick=()=>{clearInterval(timer.int);timer.running=false;timer.seconds=timer.total;timerStart.textContent='Start';timerRender()};
function populateFocus(){focusTask.innerHTML='<option value="">No specific task</option>'+state.homework.filter(x=>!x.done).map(x=>`<option>${esc(x.subject)} • ${esc(x.task)}</option>`).join('')+state.everyday.filter(x=>!x.done).map(x=>`<option>${esc(x.title)}</option>`).join('')}
function refresh(){renderHome();renderSchool();renderHomework();renderEveryday();renderExams();renderNotes();populateFocus();renderEnglish(document.querySelector('[data-english].active')?.dataset.english||'comprehension')}
renderChat();refresh();timerRender();
